# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: johnz
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ai-chatbot-app3
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ai-chatbot-backend

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.11

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true  # 允许 CORS
      - http:
          path: /chat
          method: POST
          cors: true  # 允许 CORS
      - http:
          path: /{proxy+}
          method: ANY
          cors: true  # 允许 CORS

plugins:
  - serverless-wsgi
  - serverless-python-requirements
